import React from 'react';
import { ToggleRight, ToggleLeft } from 'lucide-react';

const NotificationsSettings = ({ state, handleChange }) => {
  const toggle = (key) => handleChange(key, !state[key]);

  return (
    <div className="card animate-fade-in" style={{padding: 32, display: 'flex', flexDirection: 'column', gap: 32}}>
      <div>
        <h3 style={{fontSize: '1.25rem', fontWeight: 600, marginBottom: 8, color: 'var(--color-text-main)'}}>Delivery Channels</h3>
        <p style={{color: 'var(--color-text-secondary)', fontSize: '0.9rem', marginBottom: 24}}>Choose how you want to receive platform alerts.</p>
        
        <div style={{display: 'flex', flexDirection: 'column', gap: 16}}>
          {[
            { id: 'notifEmail', label: 'Email Notifications', desc: 'Receive updates directly to your inbox.' },
            { id: 'notifPush', label: 'Push Notifications', desc: 'Receive instant browser push notifications.' },
            { id: 'notifSms', label: 'SMS Alerts', desc: 'Receive text messages for critical security events.' }
          ].map(setting => (
            <div key={setting.id} className="flex justify-between items-center" style={{padding: '16px 20px', border: '1px solid var(--color-border)', borderRadius: 12, backgroundColor: 'var(--color-surface)'}}>
              <div>
                <div style={{fontWeight: 600, color: 'var(--color-text-main)'}}>{setting.label}</div>
                <div style={{fontSize: '0.85rem', color: 'var(--color-text-secondary)'}}>{setting.desc}</div>
              </div>
              <button onClick={() => toggle(setting.id)} style={{background: 'none', border: 'none', cursor: 'pointer'}}>
                {state[setting.id] ? <ToggleRight size={32} color="var(--color-primary)" /> : <ToggleLeft size={32} color="var(--color-text-muted)" />}
              </button>
            </div>
          ))}
        </div>
      </div>

      <hr style={{border: 'none', borderTop: '1px solid var(--color-border)'}} />

      <div>
        <h3 style={{fontSize: '1.25rem', fontWeight: 600, marginBottom: 8, color: 'var(--color-text-main)'}}>Alert Preferences</h3>
        <p style={{color: 'var(--color-text-secondary)', fontSize: '0.9rem', marginBottom: 24}}>Determine what types of events trigger notifications.</p>

        <div style={{display: 'flex', flexDirection: 'column', gap: 16}}>
          {[
            { id: 'notifCritical', label: 'Critical Alerts', desc: 'System outages, security breaches, and major errors.' },
            { id: 'notifApprovals', label: 'Approval Reminders', desc: 'Notify when a structural change requires your signature.' },
            { id: 'notifAI', label: 'AI Recommendations', desc: 'Proactive insights generated by SAMS Intelligence.' }
          ].map(setting => (
            <div key={setting.id} className="flex justify-between items-center" style={{padding: '16px 20px', border: '1px solid var(--color-border)', borderRadius: 12, backgroundColor: 'var(--color-surface)'}}>
              <div>
                <div style={{fontWeight: 600, color: 'var(--color-text-main)'}}>{setting.label}</div>
                <div style={{fontSize: '0.85rem', color: 'var(--color-text-secondary)'}}>{setting.desc}</div>
              </div>
              <button onClick={() => toggle(setting.id)} style={{background: 'none', border: 'none', cursor: 'pointer'}}>
                {state[setting.id] ? <ToggleRight size={32} color="var(--color-primary)" /> : <ToggleLeft size={32} color="var(--color-text-muted)" />}
              </button>
            </div>
          ))}
        </div>
      </div>

      <hr style={{border: 'none', borderTop: '1px solid var(--color-border)'}} />

      <div>
        <h3 style={{fontSize: '1.25rem', fontWeight: 600, marginBottom: 8, color: 'var(--color-text-main)'}}>Digests</h3>
        <div style={{display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 24, marginTop: 24}}>
          <div className="flex flex-col gap-2">
            <label style={{fontWeight: 600, fontSize: '0.9rem', color: 'var(--color-text-main)'}}>Daily Summary</label>
            <select className="input-field" value={state.notifDaily || 'none'} onChange={(e) => handleChange('notifDaily', e.target.value)}>
              <option value="none">Disabled</option>
              <option value="morning">Morning (8:00 AM)</option>
              <option value="evening">Evening (5:00 PM)</option>
            </select>
          </div>
          <div className="flex flex-col gap-2">
            <label style={{fontWeight: 600, fontSize: '0.9rem', color: 'var(--color-text-main)'}}>Weekly Report</label>
            <select className="input-field" value={state.notifWeekly || 'friday'} onChange={(e) => handleChange('notifWeekly', e.target.value)}>
              <option value="none">Disabled</option>
              <option value="monday">Monday Morning</option>
              <option value="friday">Friday Afternoon</option>
            </select>
          </div>
        </div>
      </div>

    </div>
  );
};

export default NotificationsSettings;
